name: 07-1. CI Workflow

# Trigger CI for every PR event, when PR has target branch = main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # The first job lints the code base
  lint:
    uses: omerahmaad/traing_git/.github/workflows/super-linter.yml@main

  # CI job to run a test suite on the code base
  ci:
    name: CI
    # We want to test across multiple OSs, defined by our matrix
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      # Cancel all matrix jobs if one of them fails
      fail-fast: true
      matrix:
        # our matrix for testing across node versions and OSs
        node-version: [12, 14, 16]
        os: [windows-latest, ubuntu-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure our node environment according to matrix
      - name: Setup node ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run test suite
        run: |
          npm ci
          npm run build --if-present
          npm test

      # Upload the output log file as an artifact
      - name: Create output log
        run: echo 'Test upload artifact' > output.log

      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file-${{ matrix.node-version }}-${{ matrix.os }}
          path: output.log

  # If both linting and CI succeed, we want to deploy the code to a test environment
  deploy-test:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: ci
    environment:
      name: TEST
      url: https://test.company.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download the artifact using the exact name
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: output-log-file-${{ matrix.node-version }}-${{ matrix.os }}

      # Placeholder - this step would be some action or run commands that deploys the code
      - name: Deploy to test env
        if: ${{ success() }}
        run: |
          echo "Deploying to test environment"
